
name: Run Playwright Test and Import Results into JIRA

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Choose environment'
        required: true
        type: choice
        options:
          - lle6

jobs:
  RunPlaywrightTests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
    - name: Playwright installation
      run: |
        npm init -y
        npm install -D @playwright/test@latest
        npx playwright install
        npx @playwright/test --version

    - name: List test files
      run: |
        ls -R ../
        
    - name: Run Playwright functional tests
      run: |
        npx playwright test ../tests/functional_tests --reporter=json
        # npx playwright test --reporter=json
    
    
    # - name: Save report as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: playwright-report
    #     path: playwright-report.json
        

    - name: Authenticate with Xray
      id: xray-auth
      run: |
        TOKEN=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
          -H "Content-Type: application/json" \
          -d '{"client_id": "${{ secrets.XRAY_CLIENT_ID }}", "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"}' | tr -d '"')
        echo "token=$TOKEN" >> $GITHUB_OUTPUT

    - name: Upload results to Xray
      run: |
        curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/playwright \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ steps.xray-auth.outputs.token }}" \
          -F "info={\"testExecution\": {\"testPlanKey\": \"OPS-95\", \"summary\": \"Playwright run from GitHub Actions\", \"description\": \"Automated Regression Testing \"}};type=application/json" \
          -F "results=@playwright-report.json;type=application/json"
